// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABhucwdvE5RfN_C02ESfjLgcbzSAe8jIo',
    appId: '1:972881455588:web:1370aafe783394daffbff1',
    messagingSenderId: '972881455588',
    projectId: 'chat-app-22a',
    authDomain: 'chat-app-22a.firebaseapp.com',
    storageBucket: 'chat-app-22a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvZQtcznZ_5rzQGZkp3nbvl66JA2ewdZU',
    appId: '1:972881455588:android:b35476f3bc2e9b00ffbff1',
    messagingSenderId: '972881455588',
    projectId: 'chat-app-22a',
    storageBucket: 'chat-app-22a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMtjxEPb9LDMr9zSHejbF-uJfo2XfBf5M',
    appId: '1:972881455588:ios:76fb1abbb1b4e6d3ffbff1',
    messagingSenderId: '972881455588',
    projectId: 'chat-app-22a',
    storageBucket: 'chat-app-22a.appspot.com',
    iosClientId: '972881455588-r3beh6p5p4ggje89254a36nt3257elb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
